name: Simple Pipeline

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
    outputs:
      shared_message: ${{ steps.set_message.outputs.shared_message }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Show files
        run: ls -la

      - name: Print current folder
        run: pwd

      - name: "Just test install node"
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check node version
        run: node --version

      - name: Define and print variable
        id: set_message
        run: |
          shared_message="Hello from demo-job"
          echo "demo-job variable: $shared_message"
          echo "shared_message=$shared_message" >> "$GITHUB_OUTPUT"


  demo-job-windows:
    runs-on: windows-latest
    needs: demo-job
    env:
      SHARED_MESSAGE: ${{ needs.demo-job.outputs.shared_message }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Show files
        run: dir

      - name: Print current folder
        run: cd

      - name: Print shared variable
        run: |
          Write-Host "demo-job variable from ubuntu job: $env:SHARED_MESSAGE"